name: CBuilder Unit/System Tests & C-Runtime System Tests

on:
    #push:
    #branches:
    #- "test_suite"
    workflow_dispatch:

jobs:

    languagefeatures:
        name: languagefeatures
        needs: catch2
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest-large]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: gradle
            - name: Build with Gradle
              run: ./gradlew test

    spotless:
        name: Spotless
        needs: languagefeatures
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: gradle
            - name: Spotless
              run: ./gradlew spotlessJavaCheck
